parameters:
  mailer_transport: 'smtp'
  mailer_host: '%env(MAILER_HOST)%'
  mailer_port: '%env(MAILER_PORT)%'
  mailer_encryption: '%env(MAILER_ENCRYPTION)%'
  mailer_user: '%env(MAILER_USER)%'
  mailer_password: '%env(MAILER_PASSWORD)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  Symfony\Component\DependencyInjection\ContainerInterface:
    alias: service_container

  App\Service\Strategy\EmailStrategy:
    autowire: true
    public: true

  App\Infrastructure\SendEmail:
    autowire: true
